config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root 'properties#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :stations, :dependent => :destroy
    accepts_nested_attributes_for :stations
    validates :property, presence: true
    validates :rent, presence: true
    validates :address, presence: true
    validates :building_age, presence: true
    validates :remarks, presence: true

end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = Property.new
    2.times do
      @property.stations.build
    end
  end

  def edit
    @property.stations.new
  end

  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:property, :rent, :address, :building_age, :remarks, 
                                        stations_attributes:[:id, :railway,:name,:distance])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property %>
    <%= form.text_field :property %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.number_field :rent %> yen
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :building_age %>
    <%= form.number_field :building_age %> year/years old
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>
  <hr>
  
  <%= form.fields_for :stations do |station|%>
   <h3>Name of Railway <%= station.index+1 %></h3>
   
    <div class="field">
      <%= station.label :railway, "Name of railway line" %>
      <%= station.text_field :railway %>
    </div>

    <div class="field">
      <%= station.label :name, "Station name" %>
      <%= station.text_field :name %>
    </div>

    <div class="field">
      <%= station.label :distance, "How many minutes walk" %>
      <%= station.text_field :distance %> min/mins
    </div>

  <%end%>
  <div class="actions">
    <%= form.submit "Register" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building_age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>
<hr>

<p>
  
  <% @property.stations.where.not(distance: !nil).order(:distance).limit(1).each do |f| %>
      <h3>Nearest station 1</h3>
      Name of railway line: <%=f.railway%> <br>
      Station name: <%=f.name%><br>
      How many minutes walk: <%=f.distance%> min/mins
  <%end%>
  <% @property.stations.where.not(distance: !nil).order(:distance).limit(1).offset(1).each do |f| %>
      <h3>Nearest station 2</h3>
      Name of railway line: <%=f.railway%> <br>
      Station name: <%=f.name%><br>
      How many minutes walk: <%=f.distance%> min/mins
  <%end%>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>